footer optimization and homepage redirect
cornell-dti/DesignAtCornell pull request #68
Opened 2022-04-16 15:35 UTC by syoung212

### Summary 

This PR implements the optimizes the footer and redirects users to the homepage. 

Components added:
- The footer was optimized to take out any unnecessary components and shorten it. 
- Prior, clicking on the logo took users to the explore courses page. Now it will take users back to the main homepage.

2022-04-16 15:43 UTC, katrina433 reviewed
Thanks for updating the footer! It looks good other than that there is too much whitespace. Try reducing the height of the footer.

2022-04-16 15:54 UTC, Sydney-tran reviewed
I also left a comment, but I think it would be helpful to make the email a link so that users can click on it and it automatically opens an email draft to [hello@cornelldti.org](mailto:hello@cornelldti.org). I think using mailto should work, but otherwise, looks good!

2022-04-16 15:54 UTC, Sydney-tran commented on design-at-cornell/src/footer/Footer.tsx
> +      <p>For any questions, please contact hello@cornelldti.org</p>
If possible, make the email a link so that users can click on it and it automatically opens an email draft to hello@cornelldti.org.

2022-04-17 20:30 UTC, pratyush1712 requested changes
The footer looks nice! But I think the dti (powered by) logo and the "for any questions" thing are not properly aligned
<img width="825" alt="alignment" src="https://user-images.githubusercontent.com/80096811/163730990-5efb6551-af3a-4de0-9bca-91bbc95efa64.png">
Maybe you could add some margin-bottom (or margin-top) on the dti logo (or the questions thing).

2022-04-24 20:45 UTC, katrina433 approved these changes
Looks good!

2022-04-24 20:48 UTC, pratyush1712 approved these changes

2022-04-24 20:48 UTC, merged